# Generated by Django 4.2.7 on 2024-03-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course Unit',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('course_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.courseunit')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField()),
                ('link', models.CharField(max_length=1000)),
                ('thumbnail', models.CharField(blank=True, max_length=1000)),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.week')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('parent_comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='athena.comment')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.video')),
            ],
        ),
    ]
